package org.perscholas.database;

import org.perscholas.database.entity.Order;
import org.perscholas.database.entity.OrderDetail;
import org.perscholas.database.entity.Product;

public class CreateOrderDetails {

    private OrderDAO orderDAO = new OrderDAO();
    private ProductDAO productDAO = new ProductDAO();
    private OrderDetailsDAO orderDetailsDAO = new OrderDetailsDAO();


    public void createOrderDetails() {
        // the goal is to insert a record into the order details table
        Product p = productDAO.findById(1);
        Order o = orderDAO.findById(10100);

        OrderDetail od = new OrderDetail();
        od.setProduct(p);
        od.setOrder(o);
        od.setOrderLineNumber(200);
        od.setPriceEach(5.55);
        od.setQuantutyOrdered(300);

        orderDetailsDAO.save(od);
    }


    public static void main(String[] args) {
        CreateOrderDetails cod = new CreateOrderDetails();
        cod.createOrderDetails();
    }


}